FROM ubuntu:18.04
RUN apt-get update -y && \
    apt-get install -y python3-pip python3-dev curl
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip3 install -r requirements.txt
COPY ./api.py /app/api.py
EXPOSE 5000
HEALTHCHECK --interval=5s --timeout=3s CMD curl --fail http://localhost:5000/health || exit 1
ENTRYPOINT [ "python3" ]
CMD [ "api.py" ]
