version: "3.8"

services:
  pingservice:
    build: 
      context: .
      dockerfile: build/dockerfile_ping
    image: ping-service:latest
    container_name: ping-service
    ports:
      - "8080:5000"
    networks:
      - Python-Flask-Network
  receiverservice:
    build: 
      context: .
      dockerfile: build/dockerfile_receiver
    image: receiver-service:latest
    container_name: receiver-service
    networks:
      - Python-Flask-Network
networks:
  Python-Flask-Network:
