FROM ubuntu:18.04
RUN apt-get update -y && \
    apt-get install -y python3-pip python3-dev
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip3 install -r requirements.txt
COPY ./api2.py /app/api2.py
EXPOSE 8080
ENTRYPOINT [ "python3" ]
CMD [ "api2.py" ]
